### ISSUE TITLE
Route generate conditions for RoutableInterface entities

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2714]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| BC Break? | yes
| Sulu Version | 1.3.0-RC2

#### Actual Behavior

Actual the `setRoute` method of `Sulu\Bundle\RouteBundle\Model\RoutableInterface` default implementation is not nullable. You can set the `=  null` on your custom entity but I think the Interface should be the with the `= null`. PHP will not error so this is currently no bug. Currently you can not set a condition when a route for an entity should be generated.

#### Expected Behavior

setRoute should be:

```php
public function setRoute(RouteInterface $route = null);
```

conditions could be something like this:

```yml
# Sulu Routing
sulu_route:
    mappings:
        SomeEntity:
            route_schema: /entity/{object.getTitle()}
            condition: {object.isPublished()}
```

#### Steps to Reproduce

```php
$entity->setRoute(null);
```

**Comment by danrot** [comment]
@wachterjohannes @alexander-schranz Should this be fixed with 1.4?

**Comment by wachterjohannes** [comment]
this would only work if you have call update on each entity-change. we should talk about that in deeper before fixing it.

**Comment by danrot** [comment]
@alexander-schranz Is this still something we should act on? Don't know too much about the RouteBundle...

**Comment by danrot** [comment]
@wachterjohannes @alexander-schranz Is that still something left to do?

**Comment by alexander-schranz** [comment]
Not sure about the condition but the Interface still does not allow to remove the Route from the entity.

https://github.com/sulu/sulu/blob/ade35fff4cb8ced777c726dcb730c5c5f5720960/src/Sulu/Bundle/RouteBundle/Model/RoutableInterface.php#L33-L38

but changing this at current state would be a BC break 🙈 as all need to change the implementation of that interface.

**Comment by danrot** [comment]
I still don't really get why we need that change. Without that it is hard to tell if it justifies the BC break (you know that every change is a potential BC break...)

**Comment by alexander-schranz** [comment]
@danrot but this is a bc break which will break all which use the RouteableInterface in there custom entity as autoloading will error:

Similiar Example:

```bash
php -r 'interface Test { public function test(Test $test); } class Test2 implements Test { public function test(Test $test) {} }'
```

Add allow null to  the interface the class declaration:

```bash
php -r 'interface Test { public function test(Test $test = null); } class Test2 implements Test { public function test(Test $test) {} }'
```

So all custom entities which did follow the docs: http://docs.sulu.io/en/2.0/bundles/route/ will not longer work if we change to `public function setRoute(RouteInterface $route = null);`.

Just want to mention that this is not just some internal interface we would change here we have not provide a trait for this, so basically we break any projects using the RouteBundle.

**Comment by danrot** [comment]
That was not really what I was asking for :see_no_evil: 

Would still like to know why you are suggesting this change at all.

**Comment by alexander-schranz** [comment]
@danrot sorry, if you unpublish something or remove the route from the database the `$entity->getRoute()` will still return the route as it does still exist in the memory of php.

That the route is also removed from the in memory entity `$entity->setRoute(null);` should be able to be called in that case. So if you have logic based on `if ($entity->getRoute())` or will not fail.
